#!/bin/bash
set -e

export DEGRAF_PROJECT_ROOT="${DEGRAF_PROJECT_ROOT:-/root/autodl-tmp/projects/DegrafFlowGPU}"
if [ ! -d "${DEGRAF_PROJECT_ROOT}" ]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  export DEGRAF_PROJECT_ROOT="${SCRIPT_DIR}"
fi
export DEGRAF_DATA_PATH="${DEGRAF_DATA_PATH:-/root/autodl-tmp/data/kitti/data_scene_flow}"
export DEGRAF_CALIB_PATH="${DEGRAF_CALIB_PATH:-/root/autodl-tmp/data/kitti/data_scene_flow_calib}"
export DEGRAF_INFERENCE_MODE="${DEGRAF_INFERENCE_MODE:-cpp}"
export DEGRAF_ALLOW_CPU_FALLBACK="${DEGRAF_ALLOW_CPU_FALLBACK:-0}"
export DEGRAF_RAFT_BACKEND="${DEGRAF_RAFT_BACKEND:-trt}"
export DEGRAF_ALLOW_LK_FALLBACK="${DEGRAF_ALLOW_LK_FALLBACK:-0}"
export DEGRAF_RAFT_MAX_FLOW_LENGTH="${DEGRAF_RAFT_MAX_FLOW_LENGTH:-0}"
export DEGRAF_RAFT_SAMPLE_MODE="${DEGRAF_RAFT_SAMPLE_MODE:-legacy}"
export DEGRAF_RAFT_REQUIRE_DST_IN_BOUNDS="${DEGRAF_RAFT_REQUIRE_DST_IN_BOUNDS:-0}"
export DEGRAF_RAFT_REQUIRE_SAMPLE_IN_BOUNDS="${DEGRAF_RAFT_REQUIRE_SAMPLE_IN_BOUNDS:-0}"
export DEGRAF_RAFT_SAMPLE_PADDING="${DEGRAF_RAFT_SAMPLE_PADDING:-zeros}"
export DEGRAF_POINTS_INPUT_DIR="${DEGRAF_POINTS_INPUT_DIR:-}"
export DEGRAF_MATCHES_INPUT_DIR="${DEGRAF_MATCHES_INPUT_DIR:-}"
if [ -z "${DEGRAF_RAFT_ENGINE_PATH:-}" ]; then
  if [ -f "${DEGRAF_PROJECT_ROOT}/external/RAFT/models/raft_kitti_debug_fp32.engine" ]; then
    export DEGRAF_RAFT_ENGINE_PATH="${DEGRAF_PROJECT_ROOT}/external/RAFT/models/raft_kitti_debug_fp32.engine"
  else
    export DEGRAF_RAFT_ENGINE_PATH="${DEGRAF_PROJECT_ROOT}/external/RAFT/models/raft_kitti_fp16.engine"
  fi
fi
export DEGRAF_INTERPONET_BACKEND="${DEGRAF_INTERPONET_BACKEND:-trt}"
export DEGRAF_ALLOW_EPIC_FALLBACK="${DEGRAF_ALLOW_EPIC_FALLBACK:-1}"
export DEGRAF_INTERPONET_USE_BA_MATCHES="${DEGRAF_INTERPONET_USE_BA_MATCHES:-0}"
if [ -z "${DEGRAF_INTERPONET_ENGINE_PATH:-}" ]; then
  export DEGRAF_INTERPONET_ENGINE_PATH="${DEGRAF_PROJECT_ROOT}/external/InterpoNet/models/interponet_kitti_fp32.engine"
fi
export DEGRAF_INTERPONET_DOWNSCALE="${DEGRAF_INTERPONET_DOWNSCALE:-8}"
export DEGRAF_SALIENCY_KERNEL="${DEGRAF_SALIENCY_KERNEL:-3}"
export DEGRAF_WINDOW_W="${DEGRAF_WINDOW_W:-3}"
export DEGRAF_WINDOW_H="${DEGRAF_WINDOW_H:-3}"
export DEGRAF_STEP_X="${DEGRAF_STEP_X:-9}"
export DEGRAF_STEP_Y="${DEGRAF_STEP_Y:-9}"
if [ -z "${DEGRAF_INTERPONET_EDGES_DIR:-}" ] && [ -d "${DEGRAF_PROJECT_ROOT}/external/InterpoNet/data/interponet_input" ]; then
  export DEGRAF_INTERPONET_EDGES_DIR="${DEGRAF_PROJECT_ROOT}/external/InterpoNet/data/interponet_input"
fi
export DEGRAF_INTERPONET_REQUIRE_SED="${DEGRAF_INTERPONET_REQUIRE_SED:-1}"
export DEGRAF_INTERPONET_EDGES_START_INDEX="${DEGRAF_INTERPONET_EDGES_START_INDEX:-0}"
export DEGRAF_INTERPONET_EDGES_DOWNSCALE_MODE="${DEGRAF_INTERPONET_EDGES_DOWNSCALE_MODE:-python_like}"
export DEGRAF_INTERPONET_DEBUG_DUMP_DIR="${DEGRAF_INTERPONET_DEBUG_DUMP_DIR:-}"
export DEGRAF_INTERPONET_DEBUG_DUMP_LOWRES="${DEGRAF_INTERPONET_DEBUG_DUMP_LOWRES:-0}"
export DEGRAF_INTERPONET_DEBUG_DUMP_INPUTS="${DEGRAF_INTERPONET_DEBUG_DUMP_INPUTS:-0}"
export DEGRAF_ENABLE_VARIATIONAL="${DEGRAF_ENABLE_VARIATIONAL:-1}"
export DEGRAF_VARIATIONAL_MODE="${DEGRAF_VARIATIONAL_MODE:-inprocess}"
export DEGRAF_VARIATIONAL_HARD_MODE="${DEGRAF_VARIATIONAL_HARD_MODE:-0}"
export DEGRAF_VARIATIONAL_HARD_MIN_POINTS="${DEGRAF_VARIATIONAL_HARD_MIN_POINTS:-4500}"
export DEGRAF_VARIATIONAL_HARD_RESIDUAL_THRESH="${DEGRAF_VARIATIONAL_HARD_RESIDUAL_THRESH:-6.0}"
export DEGRAF_VARIATIONAL_HARD_NITER_OUTER="${DEGRAF_VARIATIONAL_HARD_NITER_OUTER:-3}"
export DEGRAF_VARIATIONAL_HARD_GAMMA="${DEGRAF_VARIATIONAL_HARD_GAMMA:-0.80}"
export DEGRAF_VARIATIONAL_HARD_SIGMA="${DEGRAF_VARIATIONAL_HARD_SIGMA:-1.9}"
if [ -z "${OMP_NUM_THREADS:-}" ]; then
  export OMP_NUM_THREADS="${DEGRAF_OMP_NUM_THREADS:-$(nproc)}"
fi

echo "[INFO] DEGRAF_PROJECT_ROOT=${DEGRAF_PROJECT_ROOT}"
echo "[INFO] DEGRAF_DATA_PATH=${DEGRAF_DATA_PATH}"
echo "[INFO] DEGRAF_CALIB_PATH=${DEGRAF_CALIB_PATH}"
echo "[INFO] DEGRAF_INFERENCE_MODE=${DEGRAF_INFERENCE_MODE} (single-process C++ pipeline)"
echo "[INFO] DEGRAF_ALLOW_CPU_FALLBACK=${DEGRAF_ALLOW_CPU_FALLBACK}"
echo "[INFO] DEGRAF_RAFT_BACKEND=${DEGRAF_RAFT_BACKEND}"
echo "[INFO] DEGRAF_ALLOW_LK_FALLBACK=${DEGRAF_ALLOW_LK_FALLBACK}"
echo "[INFO] DEGRAF_RAFT_MAX_FLOW_LENGTH=${DEGRAF_RAFT_MAX_FLOW_LENGTH}"
echo "[INFO] DEGRAF_RAFT_SAMPLE_MODE=${DEGRAF_RAFT_SAMPLE_MODE}"
echo "[INFO] DEGRAF_RAFT_REQUIRE_DST_IN_BOUNDS=${DEGRAF_RAFT_REQUIRE_DST_IN_BOUNDS}"
echo "[INFO] DEGRAF_RAFT_REQUIRE_SAMPLE_IN_BOUNDS=${DEGRAF_RAFT_REQUIRE_SAMPLE_IN_BOUNDS}"
echo "[INFO] DEGRAF_RAFT_SAMPLE_PADDING=${DEGRAF_RAFT_SAMPLE_PADDING}"
echo "[INFO] DEGRAF_POINTS_INPUT_DIR=${DEGRAF_POINTS_INPUT_DIR:-<empty>}"
echo "[INFO] DEGRAF_MATCHES_INPUT_DIR=${DEGRAF_MATCHES_INPUT_DIR:-<empty>}"
echo "[INFO] DEGRAF_RAFT_ENGINE_PATH=${DEGRAF_RAFT_ENGINE_PATH}"
echo "[INFO] DEGRAF_INTERPONET_BACKEND=${DEGRAF_INTERPONET_BACKEND}"
echo "[INFO] DEGRAF_INTERPONET_USE_BA_MATCHES=${DEGRAF_INTERPONET_USE_BA_MATCHES}"
echo "[INFO] DEGRAF_INTERPONET_ENGINE_PATH=${DEGRAF_INTERPONET_ENGINE_PATH}"
echo "[INFO] DEGRAF_INTERPONET_DOWNSCALE=${DEGRAF_INTERPONET_DOWNSCALE}"
echo "[INFO] DEGRAF_SALIENCY_KERNEL=${DEGRAF_SALIENCY_KERNEL}"
echo "[INFO] DEGRAF_WINDOW_W=${DEGRAF_WINDOW_W}"
echo "[INFO] DEGRAF_WINDOW_H=${DEGRAF_WINDOW_H}"
echo "[INFO] DEGRAF_STEP_X=${DEGRAF_STEP_X}"
echo "[INFO] DEGRAF_STEP_Y=${DEGRAF_STEP_Y}"
echo "[INFO] DEGRAF_INTERPONET_EDGES_DIR=${DEGRAF_INTERPONET_EDGES_DIR:-<empty>}"
echo "[INFO] DEGRAF_INTERPONET_REQUIRE_SED=${DEGRAF_INTERPONET_REQUIRE_SED}"
echo "[INFO] DEGRAF_INTERPONET_EDGES_START_INDEX=${DEGRAF_INTERPONET_EDGES_START_INDEX}"
echo "[INFO] DEGRAF_INTERPONET_EDGES_DOWNSCALE_MODE=${DEGRAF_INTERPONET_EDGES_DOWNSCALE_MODE}"
echo "[INFO] DEGRAF_INTERPONET_DEBUG_DUMP_DIR=${DEGRAF_INTERPONET_DEBUG_DUMP_DIR:-<empty>}"
echo "[INFO] DEGRAF_INTERPONET_DEBUG_DUMP_LOWRES=${DEGRAF_INTERPONET_DEBUG_DUMP_LOWRES}"
echo "[INFO] DEGRAF_INTERPONET_DEBUG_DUMP_INPUTS=${DEGRAF_INTERPONET_DEBUG_DUMP_INPUTS}"
echo "[INFO] DEGRAF_ALLOW_EPIC_FALLBACK=${DEGRAF_ALLOW_EPIC_FALLBACK}"
echo "[INFO] DEGRAF_ENABLE_VARIATIONAL=${DEGRAF_ENABLE_VARIATIONAL}"
echo "[INFO] DEGRAF_VARIATIONAL_MODE=${DEGRAF_VARIATIONAL_MODE}"
echo "[INFO] DEGRAF_VARIATIONAL_HARD_MODE=${DEGRAF_VARIATIONAL_HARD_MODE}"
echo "[INFO] DEGRAF_VARIATIONAL_HARD_MIN_POINTS=${DEGRAF_VARIATIONAL_HARD_MIN_POINTS}"
echo "[INFO] DEGRAF_VARIATIONAL_HARD_RESIDUAL_THRESH=${DEGRAF_VARIATIONAL_HARD_RESIDUAL_THRESH}"
echo "[INFO] DEGRAF_VARIATIONAL_HARD_NITER_OUTER=${DEGRAF_VARIATIONAL_HARD_NITER_OUTER}"
echo "[INFO] DEGRAF_VARIATIONAL_HARD_GAMMA=${DEGRAF_VARIATIONAL_HARD_GAMMA}"
echo "[INFO] DEGRAF_VARIATIONAL_HARD_SIGMA=${DEGRAF_VARIATIONAL_HARD_SIGMA}"
echo "[INFO] OMP_NUM_THREADS=${OMP_NUM_THREADS}"

mkdir -p "${DEGRAF_PROJECT_ROOT}/data/outputs"
if command -v nvcc >/dev/null 2>&1; then
  BUILD_DIR="${DEGRAF_PROJECT_ROOT}/build_gpu"
  mkdir -p "${BUILD_DIR}"
  cd "${BUILD_DIR}"
  CMAKE_EXTRA_ARGS="${DEGRAF_CMAKE_EXTRA_ARGS:-}"
  BUILD_TYPE="${DEGRAF_CMAKE_BUILD_TYPE:-Release}"
  if [[ "${CMAKE_EXTRA_ARGS}" != *"TENSORRT_INCLUDE_DIR"* ]]; then
    TRT_INC=""
    for p in \
      "/usr/include/x86_64-linux-gnu/NvInfer.h" \
      "/usr/include/NvInfer.h" \
      "/root/autodl-tmp/pydeps/tensorrt/include/NvInfer.h" \
      "/root/miniconda3/include/NvInfer.h"; do
      if [ -f "$p" ]; then
        TRT_INC="$(dirname "$p")"
        break
      fi
    done
    TRT_NVINFER=""
    for p in \
      "/usr/lib/x86_64-linux-gnu/libnvinfer.so.10" \
      "/root/autodl-tmp/pydeps/tensorrt_libs/libnvinfer.so.10" \
      "/root/miniconda3/lib/python3.8/site-packages/tensorrt_libs/libnvinfer.so.10"; do
      if [ -f "$p" ]; then
        TRT_NVINFER="$p"
        break
      fi
    done
    TRT_NVONNX=""
    for p in \
      "/usr/lib/x86_64-linux-gnu/libnvonnxparser.so.10.13.0" \
      "/usr/lib/x86_64-linux-gnu/libnvonnxparser.so.10" \
      "/root/autodl-tmp/pydeps/tensorrt_libs/libnvonnxparser.so.10.13.0" \
      "/root/autodl-tmp/pydeps/tensorrt_libs/libnvonnxparser.so.10" \
      "/root/miniconda3/lib/python3.8/site-packages/tensorrt_libs/libnvonnxparser.so.10"; do
      if [ -f "$p" ]; then
        TRT_NVONNX="$p"
        break
      fi
    done
    if [ -n "$TRT_INC" ] && [ -n "$TRT_NVINFER" ] && [ -n "$TRT_NVONNX" ]; then
      CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} -DTENSORRT_INCLUDE_DIR=${TRT_INC} -DTENSORRT_NVINFER_LIB=${TRT_NVINFER} -DTENSORRT_NVONNXPARSER_LIB=${TRT_NVONNX}"
      export LD_LIBRARY_PATH="$(dirname "$TRT_NVINFER"):$(dirname "$TRT_NVONNX"):${LD_LIBRARY_PATH:-}"
      echo "[INFO] Auto-detected TensorRT paths."
    fi
  fi
  echo "[INFO] CUDA toolkit detected, building with USE_CUDA=ON"
  echo "[INFO] CMAKE_BUILD_TYPE=${BUILD_TYPE}"
  if [ -n "${CMAKE_EXTRA_ARGS}" ]; then
    echo "[INFO] Additional CMake args: ${CMAKE_EXTRA_ARGS}"
  fi
  cmake .. -DUSE_CUDA=ON -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_CUDA_ARCHITECTURES=75 ${CMAKE_EXTRA_ARGS}
else
  if [ "${DEGRAF_ALLOW_CPU_FALLBACK}" = "1" ]; then
    BUILD_DIR="${DEGRAF_PROJECT_ROOT}/build_cpu"
    mkdir -p "${BUILD_DIR}"
    cd "${BUILD_DIR}"
    CMAKE_EXTRA_ARGS="${DEGRAF_CMAKE_EXTRA_ARGS:-}"
    BUILD_TYPE="${DEGRAF_CMAKE_BUILD_TYPE:-Release}"
    echo "[WARN] nvcc not found, falling back to USE_CUDA=OFF (DEGRAF_ALLOW_CPU_FALLBACK=1)"
    echo "[INFO] CMAKE_BUILD_TYPE=${BUILD_TYPE}"
    if [ -n "${CMAKE_EXTRA_ARGS}" ]; then
      echo "[INFO] Additional CMake args: ${CMAKE_EXTRA_ARGS}"
    fi
    cmake .. -DUSE_CUDA=OFF -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" ${CMAKE_EXTRA_ARGS}
  else
    echo "[ERROR] nvcc not found. Refusing CPU fallback because DEGRAF_ALLOW_CPU_FALLBACK=0."
    echo "[ERROR] Install CUDA toolkit or explicitly set DEGRAF_ALLOW_CPU_FALLBACK=1."
    exit 1
  fi
fi
make -j"$(nproc)"
echo "[INFO] degraf_flow args: $*"
./degraf_flow "$@"
